import type { StoryNode } from "./types";

const nodes: StoryNode[] = [
  {
    id: "ch1",
    speaker: "n",
    bg: "night",
    ira: null,
    sasha: null,
    cg: null,
    music: "quiet",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "I", title: "МЭТЧ", hint: "сначала был чат" },
    text: "",
    next: "app1",
  },
  {
    id: "app1",
    speaker: "n",
    bg: "night",
    music: "quiet",
    ambience: "home",
    text: "Вечер был слишком обычный, чтобы ждать от него сюжет. Я листал анкеты большим пальцем — тем жестом, в котором нет ни надежды, ни гордости.",
    next: "app2",
  },
  {
    id: "app2",
    speaker: "n",
    text: "Ира. На фото она смеялась не в камеру, а кому-то, кого не было в кадре. В тексте — коротко, без девиза. Я написал первым, потому что иначе не написал бы никогда.",
    next: "app3",
  },
  {
    id: "app3",
    speaker: "n",
    ui: "chat",
    text: "Ответ пришёл быстрее, чем я успел спрятать телефон.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
    ],
    choices: [
      { text: "«Второе: у вас смех на фото не для анкеты.»", next: "app4a", warmth: 2 },
      { text: "«Второе: куда идут, когда снег ведёт себя слишком серьёзно?»", next: "app4b", warmth: 2 },
      { text: "«Второе: просто здравствуйте. Без плана.»", next: "app4c", warmth: 1 },
    ],
  },
  {
    id: "app4a",
    speaker: "n",
    ui: "chat",
    text: "Она ответила сразу. Без смайлика-щита.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: у вас смех на фото не для анкеты." },
      { from: "ira", text: "Жизнь — анкета, только без кнопки «скрыть». Но спасибо. Это почти комплимент." },
    ],
    next: "app5",
  },
  {
    id: "app4b",
    speaker: "n",
    ui: "chat",
    text: "Она, кажется, ждала именно этот вопрос.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: куда идут, когда снег ведёт себя слишком серьёзно?" },
      { from: "ira", text: "В кофейню у угла. Жёлтый свет, на вывеске от холода половина букв. Я там часто бываю с тетрадью." },
    ],
    next: "app5",
  },
  {
    id: "app4c",
    speaker: "n",
    ui: "chat",
    text: "Без плана оказалось правильной стратегией.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: просто здравствуйте. Без плана." },
      { from: "ira", text: "Без плана — это уже план. Мне нравится." },
    ],
    next: "app5",
  },
  {
    id: "app5",
    speaker: "n",
    ui: "chat",
    text: "Дальше писалось само. Не остроумно напоказ — скорее как два человека, которые узнали друг друга раньше, чем успели представиться.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
    ],
    choices: [
      { text: "«Да. Кофейня у угла, после восьми?»", next: "app6", warmth: 2 },
      { text: "«Да. Только я могу оказаться скучнее анкеты.»", next: "app6b", warmth: 1 },
      { text: "«Можно подумать до завтра.»", next: "app6c" },
    ],
  },
  {
    id: "app6",
    speaker: "n",
    ui: "chat",
    text: "Общее нашлось сразу. Его не пришлось добывать.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Да. Кофейня у угла, после восьми?" },
      { from: "ira", text: "Угла хватит. Восьми хватит. Если будете мокрым от снега — я не обижусь." },
    ],
    next: "app7",
  },
  {
    id: "app6b",
    speaker: "n",
    ui: "chat",
    text: "Общее нашлось сразу. Его не пришлось добывать.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Да. Только я могу оказаться скучнее анкеты." },
      { from: "ira", text: "Анкета всегда врёт в одну сторону. Приходите. Разберёмся на месте." },
    ],
    next: "app7",
  },
  {
    id: "app6c",
    speaker: "n",
    ui: "chat",
    text: "Я написал «подумать». Она написала так, что думать стало незачем.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Можно подумать до завтра." },
      { from: "ira", text: "Можно. А можно просто прийти. Кофейня у угла, после восьми. Я буду с тетрадью — чтобы было куда смотреть, если вдруг страшно." },
    ],
    next: "app7",
  },
  {
    id: "app7",
    speaker: "n",
    ui: undefined,
    chat: undefined,
    text: "Мы ещё не видели друг друга. А вайб уже сидел между сообщениями — как третий собеседник, которому не нужно представиться.",
    next: "ch2",
  },
  {
    id: "ch2",
    speaker: "n",
    bg: "street",
    ira: null,
    sasha: null,
    cg: null,
    music: "snow",
    ambience: "snow",
    ui: "chapter",
    chapter: { n: "II", title: "Кофейня", hint: "первый вечер" },
    text: "",
    next: "s1",
  },
  {
    id: "s1",
    speaker: "n",
    bg: "street",
    ira: null,
    sasha: null,
    cg: null,
    music: "snow",
    ambience: "snow",
    text: "Снег шёл уже третий час. Не открыточный — мокрый, тяжёлый, такой, от которого пальто становится на килограмм тяжелее, а мысли — короче.",
    next: "s2",
  },
  {
    id: "s2",
    speaker: "n",
    text: "Я шёл на свидание привычным маршрутом, как ходят на экзамен, который сам назначил. В кармане лежал телефон с чатом. В голове — все способы опоздать и все способы сбежать.",
    next: "s3",
  },
  {
    id: "s3",
    speaker: "n",
    bg: "street",
    text: "Маленькая кофейня. Жёлтый свет, мокрые стёкла, на вывеске от холода осталась только половина букв. Внутри кто-то жил обычной жизнью — и это вдруг показалось важным.",
    next: "s4",
  },
  {
    id: "s4",
    speaker: "n",
    bg: "cafe-brick",
    music: "cafe",
    ambience: "cafe",
    text: "Тёплое дерево, запах эспрессо, чужие пальто на крючках. Снег за дверью остался как чужая страна.",
    next: "s5",
  },
  {
    id: "s5",
    speaker: "n",
    ira: "thoughtful",
    text: "За столом у окна сидела женщина в кремовом свитере и что-то писала в тетради, не поднимая головы. Напротив неё — пустая чашка и пустое место. Как в сообщении.",
    next: "ask",
  },
  {
    id: "ask",
    speaker: "n",
    ira: "thoughtful",
    text: "Можно было сказать имя. Можно было постоять. Можно было сделать вид, что перепутал кофейню.",
    choices: [
      { text: "«Ира?»", next: "sit1", warmth: 1 },
      { text: "Постоять у стойки. Вдруг это не она.", next: "bar1" },
      { text: "Развернуться. Ещё не поздно.", next: "leave1" },
    ],
  },

  {
    id: "leave1",
    speaker: "n",
    ira: null,
    bg: "street",
    music: "quiet",
    ambience: "snow",
    text: "Дверь закрылась за спиной мягко, как чужая книга. Снег сразу вернул меня себе.",
    next: "leave2",
  },
  {
    id: "leave2",
    speaker: "n",
    text: "Через стекло я ещё секунду видел кремовый свитер и наклонённую голову. Потом окно запотело — и история, которой не случилось, стала просто тёплым пятном в холоде.",
    next: "leave3",
  },
  {
    id: "leave3",
    speaker: "n",
    text: "Иногда знакомство начинается с того, что ты не заходишь. Это тоже выбор. Просто очень тихий.",
    ending: "missed",
  },

  {
    id: "bar1",
    speaker: "n",
    ira: "thoughtful",
    text: "Я встал у стойки, сделал вид, что изучаю меню, которое знал наизусть с прошлого месяца. Она писала ещё с минуту, потом подняла глаза.",
    next: "bar2",
  },
  {
    id: "bar2",
    speaker: "ira",
    ira: "smile",
    text: "Саша? Я вас почти не узнала в снегу. Тут свободно. Я вас и ждала — только тетрадь не двигайте.",
    next: "bar3",
  },
  {
    id: "bar3",
    speaker: "sasha",
    sasha: "awkward",
    text: "Тетрадь не трону. Насчёт снега — он меня немного переиграл по пути.",
    next: "sit2",
  },

  {
    id: "sit1",
    speaker: "ira",
    ira: "smile",
    text: "Я. А вы — мокрый Саша из приложения. Садитесь. Только не двигайте тетрадь — там держится вся моя сегодняшняя дисциплина.",
    next: "sit2",
  },
  {
    id: "sit2",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "cafe",
    text: "Я сел. Между нами лежала тетрадь, две чашки на цветочных блюдцах и то странное молчание, в котором ещё ничего нельзя испортить.",
    next: "sit3",
  },
  {
    id: "sit3",
    speaker: "ira",
    ira: "smile",
    text: "Ира. Живая. Если вдруг решите обращаться по имени, а не «девушка из чата».",
    next: "sit4",
  },
  {
    id: "sit4",
    speaker: "sasha",
    sasha: "smile",
    text: "Саша. Девушка из чата тоже хорошо звучит, но Ира — лучше.",
    next: "sit5",
  },
  {
    id: "sit5",
    speaker: "ira",
    ira: "laugh",
    sasha: null,
    text: "Тогда Саша. Вы всегда приходите, когда снег начинает себя слишком серьёзно вести, или это я так удачно написала про кофейню?",
    next: "open",
  },
  {
    id: "open",
    speaker: "n",
    ira: "smile",
    text: "Официант уже шёл. Оставалось решить, с чего начинается разговор у людей, которые уже здоровались пальцами.",
    choices: [
      { text: "«Что пишете?»", next: "write1", warmth: 2 },
      { text: "«Снег сегодня какой-то личный.»", next: "snowtalk1", warmth: 1 },
      { text: "Просто заказать кофе и помолчать", next: "quiet1" },
    ],
  },

  {
    id: "write1",
    speaker: "ira",
    ira: "thoughtful",
    text: "Письма, которые не отправлю. Иногда списки. Сегодня — список причин не идти домой сразу.",
    next: "write2",
  },
  {
    id: "write2",
    speaker: "sasha",
    sasha: "awkward",
    text: "И как, список работает?",
    next: "write3",
  },
  {
    id: "write3",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Пока вы сели — да. Это уже пункт.",
    next: "merge1",
  },

  {
    id: "snowtalk1",
    speaker: "ira",
    ira: "laugh",
    text: "Личный снег. Запомню. У меня сапоги уже написали заявление об увольнении.",
    next: "snowtalk2",
  },
  {
    id: "snowtalk2",
    speaker: "sasha",
    sasha: "laugh",
    text: "Моё пальто тоже требует переговоров. Я шёл якобы на минуту. Из чата это звучало смелее.",
    next: "snowtalk3",
  },
  {
    id: "snowtalk3",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Минуты в такую погоду врут. Это их профессия.",
    next: "merge1",
  },

  {
    id: "quiet1",
    speaker: "n",
    ira: "thoughtful",
    text: "Мы пили молча. Снег царапал стекло. Это не было неловко — скорее как два человека, которые уже знакомы наполовину.",
    next: "quiet2",
  },
  {
    id: "quiet2",
    speaker: "ira",
    ira: "smile",
    text: "Вы всегда такой молчаливый, или это снег на вас так действует?",
    next: "quiet3",
  },
  {
    id: "quiet3",
    speaker: "sasha",
    sasha: "awkward",
    text: "Снег. И ещё я не хотел спугнуть человека с тетрадью. В чате вы казались спокойнее. Вживую — серьёзнее.",
    next: "merge1",
  },

  {
    id: "merge1",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "cafe",
    text: "Принесли кофе. У неё — без сахара. У меня — с сахаром, хотя я всегда говорю, что «почти не кладу».",
    next: "merge2",
  },
  {
    id: "merge2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Забавно. Люди на первых встречах либо становятся честнее, либо начинают рассказывать биографию. Вы какой?",
    next: "bio",
  },
  {
    id: "bio",
    speaker: "n",
    text: "Честность в восемь вечера — скользкая вещь. Но стол был маленький, и врать за ним было бы странно.",
    choices: [
      { text: "«Шёл на свидание. Честно. Немного боюсь.»", next: "honest1", warmth: 1 },
      { text: "«Ищу укрытие от судьбы. Пока только от снега.»", next: "joke1", warmth: 2 },
      { text: "«Работа рядом. Тут кофе лучше, чем в офисе.»", next: "work1" },
    ],
  },

  {
    id: "honest1",
    speaker: "ira",
    ira: "tender",
    text: "Хороший ответ. Я тоже не планировала никого знакомить так быстро. Просто рука замёрзла, и тетрадь сама открылась.",
    next: "deep1",
  },
  {
    id: "joke1",
    speaker: "ira",
    ira: "laugh",
    text: "От судьбы это заведение слабовато. От снега — вполне. Садитесь удобнее, раз уж укрылись.",
    next: "deep1",
  },
  {
    id: "work1",
    speaker: "ira",
    ira: "smile",
    text: "Офисный кофе — отдельный вид жестокости. Я вас понимаю.",
    next: "deep1",
  },

  {
    id: "deep1",
    speaker: "n",
    ira: "thoughtful",
    sasha: null,
    text: "За окном фонарь тонул в белом. Казалось, город уменьшился до этого стола — и это было не страшно.",
    next: "deep2",
  },
  {
    id: "deep2",
    speaker: "ira",
    ira: "smile",
    text: "Знаете, что мне нравится в первых встречах? Можно сказать правду: анкета уже соврала за нас всё лишнее.",
    next: "deep3",
  },
  {
    id: "deep3",
    speaker: "n",
    text: "Она крутила ложку. Свитер чуть съехал с плеча, и она поправила его так, будто это тоже было частью мысли.",
    choices: [
      { text: "«Тогда давайте правду. Что вы делаете в этом городе?»", next: "city1", warmth: 1 },
      { text: "«А если снег не кончится до весны?»", next: "if1", warmth: 2 },
      { text: "«Вы смеётесь так, будто уже решили, что я не страшный.»", next: "flirt1", warmth: 1 },
    ],
  },

  {
    id: "city1",
    speaker: "ira",
    ira: "thoughtful",
    text: "Живу. Работаю. Иногда убегаю в такие места, где можно писать и не объяснять, зачем. А вы?",
    next: "city2",
  },
  {
    id: "city2",
    speaker: "sasha",
    sasha: "warm",
    text: "Похоже. Только вместо тетради у меня обычно экран. Сегодня экран проиграл окну.",
    next: "phone1",
  },

  {
    id: "if1",
    speaker: "ira",
    ira: "surprise",
    text: "Тогда придётся научиться танцевать в сапогах. Или переехать в эту кофейню совсем.",
    next: "if2",
  },
  {
    id: "if2",
    speaker: "sasha",
    sasha: "laugh",
    text: "Я бронирую стол у окна. Вы — тетрадь. Справедливо.",
    next: "if3",
  },
  {
    id: "if3",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Справедливо. И немного опасно: так начинаются привычки.",
    next: "phone1",
  },

  {
    id: "flirt1",
    speaker: "ira",
    ira: "shy",
    text: "Я ещё не решила. Но пальто у вас честное, а это уже что-то.",
    next: "flirt2",
  },
  {
    id: "flirt2",
    speaker: "sasha",
    sasha: "awkward",
    text: "Пальто будет польщено. Оно редко получает комплименты.",
    next: "phone1",
  },

  {
    id: "phone1",
    speaker: "n",
    ira: "surprise",
    sasha: null,
    text: "Телефон на столе коротко вспыхнул. Ира взглянула на экран, и на секунду стала человеком с другой жизнью — той, что была до этого стола.",
    next: "phone2",
  },
  {
    id: "phone2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Друзья. «Ты ещё придёшь?» Я обещала заехать. Но снег… и кофе… и вы тут сидите, как пункт из списка.",
    next: "stay",
  },
  {
    id: "stay",
    speaker: "n",
    ira: "thoughtful",
    text: "Можно было отпустить. Можно было попросить остаться. Между этими двумя фразами обычно и живёт вечер.",
    choices: [
      { text: "«Останься. Снег всё равно не кончится.»", next: "stayyes", warmth: 2 },
      { text: "«Могу проводить, если решите идти.»", next: "walkoffer", warmth: 1 },
      { text: "«Если надо — идите. Я не держу.»", next: "release1" },
    ],
  },

  {
    id: "stayyes",
    speaker: "ira",
    ira: "tender",
    text: "Напишу, что сугробы взяли меня в заложники. Это почти правда.",
    next: "after1",
  },
  {
    id: "walkoffer",
    speaker: "ira",
    ira: "smile",
    text: "Проводить — это уже не «случайно сели». Это уже маршрут.",
    next: "after1",
  },
  {
    id: "release1",
    speaker: "ira",
    ira: "smile",
    text: "Вежливый Саша. Хорошо. Тогда я останусь ещё на одну чашку — уже не из вежливости.",
    next: "after1",
  },

  {
    id: "after1",
    speaker: "n",
    ira: "smile",
    bg: "cafe",
    music: "cafe",
    text: "Вторая чашка пришла сама, без заказа, как будто кофейня тоже поняла, что вечер не окончен.",
    next: "after2",
  },
  {
    id: "after2",
    speaker: "ira",
    ira: "laugh",
    text: "Расскажите что-нибудь ненужное. Не резюме. Например, какой у вас любимый бесполезный навык.",
    next: "skill",
  },
  {
    id: "skill",
    speaker: "n",
    text: "Ненужное — самое нужное в знакомстве.",
    choices: [
      { text: "«Умею угадывать, когда кто-то хочет ещё кофе.»", next: "skill1", warmth: 1 },
      { text: "«Запоминаю песни из чужих наушников в метро.»", next: "skill2", warmth: 2 },
      { text: "«Серьёзно делать вид, что разбираюсь в винах.»", next: "skill3", warmth: 1 },
    ],
  },
  {
    id: "skill1",
    speaker: "ira",
    ira: "smile",
    text: "Опасный навык. Я как раз хотела. Вы маг или просто внимательный?",
    next: "close1",
  },
  {
    id: "skill2",
    speaker: "ira",
    ira: "tender",
    text: "Это красиво и немного грустно. Как коллекция жизней, которые вам не принадлежат.",
    next: "close1",
  },
  {
    id: "skill3",
    speaker: "ira",
    ira: "laugh",
    text: "«Нотки леса и лёгкое разочарование». Я так тоже умею.",
    next: "close1",
  },

  {
    id: "close1",
    speaker: "n",
    ira: "smile",
    text: "Снег за окном стал реже, будто выдохнул. Кофейня поредела. Остались те, кому некуда спешить, и те, кто делает вид, что некуда спешить.",
    next: "close2",
  },
  {
    id: "close2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Скоро закроют. Можно разойтись, как приличные взрослые. Можно ещё немного украсть у погоды.",
    next: "fork",
  },
  {
    id: "fork",
    speaker: "n",
    ira: "smile",
    text: "Вечер стоял на развилке — тонкой, как след на снегу.",
    choices: [
      { text: "«Прогуляемся? Пока снег не передумал.»", next: "park1", warmth: 2 },
      { text: "«Сидим, пока нас не выгонят.»", next: "late1", warmth: 1 },
      { text: "«Давайте хотя бы обменяемся номерами.»", next: "num1" },
    ],
  },

  {
    id: "park1",
    speaker: "n",
    bg: "park",
    ira: "smile",
    sasha: null,
    music: "snow",
    ambience: "snow",
    text: "Парк был белым и пустым. Берёзы стояли как люди, которые тоже не знали, куда деть руки. Скамейка тонула в сугробе по пояс.",
    next: "park2",
  },
  {
    id: "park2",
    speaker: "ira",
    ira: "laugh",
    text: "Если мы сейчас упадём в сугроб, это будет очень литературно и очень мокро.",
    next: "park3",
  },
  {
    id: "park3",
    speaker: "n",
    ira: "smile",
    text: "Она шла рядом, иногда задевая рукавом. Снег падал ей в волосы и сразу становился своим.",
    choices: [
      { text: "Предложить руку, когда она поскальзывается", next: "hand1", warmth: 2 },
      { text: "«Можно я расскажу, что боялся сюда зайти?»", next: "fear1", warmth: 1 },
      { text: "Идти молча и просто быть рядом", next: "silent1", warmth: 1 },
    ],
  },
  {
    id: "hand1",
    speaker: "n",
    ira: "shy",
    text: "Её пальцы были холодными, и она не отобрала руку сразу — только посмотрела так, будто проверяла, не испугаюсь ли я собственной смелости.",
    next: "hand2",
  },
  {
    id: "hand2",
    speaker: "ira",
    ira: "tender",
    text: "Тёплая ладонь в такой снег — это уже почти признание. Не пугайтесь, я преувеличиваю. Немного.",
    next: "endgate",
  },
  {
    id: "fear1",
    speaker: "sasha",
    sasha: "awkward",
    text: "Я почти ушёл. Подумал, что мешаю человеку с тетрадью. Хорошо, что не ушёл.",
    next: "fear2",
  },
  {
    id: "fear2",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Хорошо. Я тоже почти написала «занято» на лице. Не написала.",
    next: "endgate",
  },
  {
    id: "silent1",
    speaker: "n",
    ira: "tender",
    text: "Молчание оказалось удобным, как шарф. Иногда знакомство — это просто два человека, которые не торопят тишину.",
    next: "endgate",
  },

  {
    id: "late1",
    speaker: "n",
    bg: "cg-cafe",
    ira: null,
    sasha: null,
    cg: "cg-cafe",
    music: "warm",
    ambience: "cafe",
    text: "Нас не выгнали сразу. Лампа над столом сделала из нас двух людей, которые уже выглядят как «мы», если не присматриваться.",
    next: "late2",
  },
  {
    id: "late2",
    speaker: "ira",
    cg: "cg-cafe",
    text: "Если завтра утром я решу, что вам это приснилось — не верьте. Я была. Вы были. Кофе был слишком сладкий, это ваша вина.",
    next: "endgate",
  },

  {
    id: "num1",
    speaker: "ira",
    ira: "smile",
    bg: "cafe-brick",
    cg: null,
    text: "Номер — это обещание без даты. Я люблю такие: они не давят и не исчезают.",
    next: "num2",
  },
  {
    id: "num2",
    speaker: "n",
    ira: "tender",
    text: "Мы обменялись телефонами на обороте её страницы. Почерк и правда был серьёзный.",
    next: "endgate",
  },

  {
    id: "endgate",
    speaker: "n",
    cg: null,
    text: "Ночь решила за нас остальное.",
    next: "route",
  },
  {
    id: "route",
    speaker: "n",
    text: "",
    next: "together1",
  },

  {
    id: "together1",
    speaker: "n",
    bg: "car",
    ira: "tender",
    sasha: "warm",
    cg: null,
    music: "warm",
    ambience: "car",
    text: "Потом была машина, тёплая до стыда после улицы. Снег колотил в стекло, как будто хотел ещё раз войти в историю.",
    next: "together2",
  },
  {
    id: "together2",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Не уезжай сразу. Посидим. Пусть дворники поработают за нас.",
    next: "together3",
  },
  {
    id: "together3",
    speaker: "n",
    ira: null,
    sasha: null,
    cg: "cg-car",
    text: "Она положила голову ему на плечо. Снег на стекле чертил карту города, который больше не имел значения.",
    next: "together4",
  },
  {
    id: "together4",
    speaker: "sasha",
    sasha: "warm",
    text: "Хорошо. Пока шёл снег — мы никуда не опаздывали.",
    next: "ch3",
  },

  {
    id: "ch3",
    speaker: "n",
    bg: "cafe-brick",
    ira: null,
    sasha: null,
    cg: null,
    music: "cafe",
    ambience: "cafe",
    ui: "chapter",
    chapter: { n: "III", title: "Договор", hint: "две недели спустя" },
    text: "",
    next: "doc1",
  },
  {
    id: "doc1",
    speaker: "n",
    bg: "cafe-brick",
    ira: "smile",
    sasha: null,
    cg: null,
    music: "cafe",
    ambience: "cafe",
    text: "Через две недели мы сидели в той же кофейне, как люди, которые уже имеют право на «наше место».",
    next: "doc2",
  },
  {
    id: "doc2",
    speaker: "ira",
    ira: "laugh",
    text: "Слушай. Давай сделаем это по-взрослому. Совсем чуть-чуть по-взрослому.",
    next: "doc3",
  },
  {
    id: "doc3",
    speaker: "sasha",
    sasha: "awkward",
    ira: "laugh",
    text: "Боюсь спрашивать.",
    next: "doc4",
  },
  {
    id: "doc4",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Документ. Что мы будем парень и девушка. И будем встречаться. На бумаге — чтобы никто не слинял в «ну мы так, общаемся».",
    next: "doc5",
  },
  {
    id: "doc5",
    speaker: "n",
    ira: "smile",
    text: "Она достала из сумки нормальный лист. Не салфетку. Серьёзность была смешной — и от этого настоящей.",
    choices: [
      { text: "«Где ручка. Я готов.»", next: "docpaper", warmth: 2 },
      { text: "«Добавим пункт про кофе по воскресеньям.»", next: "docpaper", warmth: 2 },
      { text: "«Это шутка? …Хорошая. Давай.»", next: "docpaper", warmth: 1 },
    ],
  },
  {
    id: "docpaper",
    speaker: "n",
    ira: null,
    sasha: null,
    ui: "contract",
    signed: false,
    text: "На листе было мало слов. Их хватало.",
    next: "docsign",
  },
  {
    id: "docsign",
    speaker: "n",
    ui: "contract",
    signed: false,
    text: "Осталось поставить имена. Как в настоящей жизни, только честнее.",
    choices: [
      { text: "Подписать", next: "docdone", warmth: 1 },
    ],
  },
  {
    id: "docdone",
    speaker: "n",
    ui: "contract",
    signed: true,
    text: "Чернила чуть размазались. Это тоже вошло в договор.",
    next: "doc6",
  },
  {
    id: "doc6",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    ui: undefined,
    signed: undefined,
    text: "Вот. Теперь нельзя делать вид, что мы друг другу не должны хотя бы честности.",
    next: "doc7",
  },
  {
    id: "doc7",
    speaker: "sasha",
    sasha: "warm",
    ira: "tender",
    text: "Я и так не собирался.",
    next: "chDrive",
  },

  {
    id: "chDrive",
    speaker: "n",
    bg: "drive",
    ira: null,
    sasha: null,
    cg: "drive",
    music: "warm",
    ambience: "car",
    ui: "chapter",
    chapter: { n: "IV", title: "За рулём", hint: "Поло, потом Тепсла" },
    text: "",
    next: "drive1",
  },
  {
    id: "drive1",
    speaker: "n",
    bg: "drive",
    ira: null,
    sasha: null,
    cg: "drive",
    music: "warm",
    ambience: "car",
    text: "Первое время она забирала меня на своей рабочей — фольксваген Поло. Та, на которой каждый день едет на работу. Та, в которой мы катались вначале. Её руки на руле, Нижний за стеклом.",
    next: "drive2",
  },
  {
    id: "drive2",
    speaker: "ira",
    ira: null,
    cg: "drive",
    text: "Садись. Поло знает этот город лучше нас. Ты пока смотри в окно и не спорь с маршрутом.",
    next: "drive3",
  },
  {
    id: "drive3",
    speaker: "n",
    cg: "drive",
    text: "Мы катались без цели, которая призналась бы вслух. Она вела. Я учился быть пассажиром — это тоже близость.",
    choices: [
      { text: "Смотреть на её руки на руле", next: "drive4a", warmth: 2 },
      { text: "Включить что-нибудь тихое", next: "drive4b", warmth: 1 },
      { text: "«Везде, куда ты.»", next: "drive4c", warmth: 2 },
    ],
  },
  {
    id: "drive4a",
    speaker: "n",
    cg: "drive",
    text: "Руки на руле были спокойнее моих мыслей. Я вдруг понял, что мне не нужно решать, куда едем. Достаточно быть рядом.",
    next: "drive5",
  },
  {
    id: "drive4b",
    speaker: "ira",
    cg: "drive",
    text: "Тихое — это ты сейчас. Поло и так шумит за двоих.",
    next: "drive5",
  },
  {
    id: "drive4c",
    speaker: "ira",
    cg: "drive",
    text: "Опасно так говорить человеку за рулём. Он может поехать далеко.",
    next: "drive5",
  },
  {
    id: "drive5",
    speaker: "n",
    bg: "tesla",
    ira: null,
    sasha: null,
    cg: "tesla",
    music: "home",
    ambience: "car",
    text: "Потом купили нашу — в Беларуси. Чёрная, тихая, в подземке ещё чернее. В документах — Tesla. Слово стояло как чужое имя на бейджике: вроде твоё, а рот его не берёт.",
    next: "driveName",
  },
  {
    id: "driveName",
    speaker: "n",
    cg: "tesla",
    music: "home",
    ambience: "car",
    text: "Пригнали в Нижний. Мороз, сиденья уже греют. Ира сказала «тёплая Tesla» — и язык сам склеил это в одно, раньше, чем мы успели пошутить.",
    next: "driveName2",
  },
  {
    id: "driveName2",
    speaker: "ira",
    cg: "tesla",
    text: "Тёпсла. Тесла. Да какая разница, она и так тёплая.",
    next: "driveName3",
  },
  {
    id: "driveName3",
    speaker: "n",
    cg: "tesla",
    text: "Разница была. Каламбур, который не надо объяснять чужим. Tesla + тёплая. Тепсла.",
    choices: [
      { text: "«Тепсла. Записали.»", next: "driveNameA", warmth: 2 },
      { text: "«В паспорте Tesla. Дома — как скажешь.»", next: "driveNameB", warmth: 1 },
      { text: "Повторить ещё раз, чтобы не развинтилось", next: "driveNameC", warmth: 1 },
    ],
  },
  {
    id: "driveNameA",
    speaker: "ira",
    cg: "tesla",
    text: "Записали. Пусть смеются те, у кого машина без имени.",
    next: "drive6",
  },
  {
    id: "driveNameB",
    speaker: "ira",
    cg: "tesla",
    text: "Правильно. Документы — для ГАИ. Имена — для нас.",
    next: "drive6",
  },
  {
    id: "driveNameC",
    speaker: "sasha",
    cg: "tesla",
    text: "Тепсла. Ещё раз: Тепсла. Теперь не отобрать.",
    next: "drive6",
  },
  {
    id: "drive6",
    speaker: "ira",
    cg: "tesla",
    text: "Я всё равно сяду первой. Привычка Поло сильнее кожи сидений.",
    next: "drive7",
  },
  {
    id: "drive7",
    speaker: "sasha",
    cg: "tesla",
    text: "Тогда я снова смотрю в окно. Только теперь окно наше.",
    next: "ch4",
  },

  {
    id: "ch4",
    speaker: "n",
    bg: "castle",
    ira: null,
    sasha: null,
    cg: null,
    music: "warm",
    ambience: "none",
    ui: "chapter",
    chapter: { n: "V", title: "Полгода", hint: "как во сне" },
    text: "",
    next: "epi1",
  },
  {
    id: "epi1",
    speaker: "n",
    bg: "castle",
    ira: null,
    sasha: null,
    cg: null,
    music: "warm",
    ambience: "none",
    text: "Потом полгода шли как во сне. То там, то тут. Всё было круто — и это слово вдруг перестало быть стыдным.",
    next: "epi2",
  },
  {
    id: "epi2",
    speaker: "n",
    bg: "gate",
    text: "Была кирпичная арка и ветер. Мы смеялись в камеру, как люди, которым уже не нужно знакомиться.",
    next: "epi3",
  },
  {
    id: "epi3",
    speaker: "n",
    bg: "bison",
    text: "Было поле и огромный зубр на горизонте — шутка размером с небо, которую мы забрали себе.",
    next: "epi4",
  },
  {
    id: "epi4",
    speaker: "n",
    bg: "wheat",
    text: "Было поле в золоте, где она показала пальцами «победа», хотя побеждать уже было некого — только вечер.",
    next: "epi5",
  },
  {
    id: "epi5",
    speaker: "n",
    bg: "river",
    text: "Была река, тихая, с ивами. И чьи-то вёсла. И мысль, что всё это началось с чата и стула у окна.",
    next: "epi6",
  },
  {
    id: "epi6",
    speaker: "n",
    bg: "car",
    text: "Была дорога длиннее разговора. Мы ехали и молчали так, как молчат только свои.",
    next: "epi7",
  },
  {
    id: "epi7",
    speaker: "n",
    bg: "red",
    text: "Был зал, где красный свет режет темноту. В такой темноте легко стать ближе — и не объяснять зачем.",
    next: "epi8",
  },
  {
    id: "epi8",
    speaker: "n",
    bg: "sunset",
    text: "Был закат на старой мостовой. Солнце ударило в глаза, и мы всё равно не отвернулись.",
    next: "ch5",
  },
  {
    id: "epi9",
    speaker: "n",
    bg: "sunset",
    text: "Так мы ходили — то там, то тут — пока чужие стены не стали тесными.",
    next: "ch5",
  },

  {
    id: "ch5",
    speaker: "n",
    bg: "rental",
    ira: null,
    sasha: null,
    cg: null,
    music: "home",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "VI", title: "Дом", hint: "новоселье, потом Альф" },
    text: "",
    next: "rent1",
  },
  {
    id: "rent1",
    speaker: "n",
    bg: "rental",
    ira: "smile",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "Сначала была съёмная. Нижний, чужая кухня, наши кружки. Ключ, который ещё не привык к карману.",
    next: "rent2",
  },
  {
    id: "rent2",
    speaker: "ira",
    ira: "laugh",
    text: "Слышишь? Это не соседи. Это мы гремим чужими тарелками, как своими.",
    next: "rent3",
  },
  {
    id: "rent3",
    speaker: "n",
    ira: "smile",
    text: "Первый вечер в четырёх стенах, которые пока не наши. Можно было делать вид, что мы умеем жить.",
    choices: [
      { text: "Приготовить что-нибудь простое", next: "rent4a", warmth: 1 },
      { text: "Разобрать коробки до полуночи", next: "rent4b", warmth: 1 },
      { text: "Сесть на пол и ничего не успевать", next: "rent4c", warmth: 2 },
    ],
  },
  {
    id: "rent4a",
    speaker: "sasha",
    sasha: "warm",
    ira: "smile",
    text: "Я умею две вещи: кофе и вид, что так и задумано. На ужин этого хватит.",
    next: "rent5",
  },
  {
    id: "rent4b",
    speaker: "ira",
    ira: "thoughtful",
    sasha: null,
    text: "Если мы сейчас всё разложим, утром будет казаться, что мы тут давно. Я не против обмана.",
    next: "rent5",
  },
  {
    id: "rent4c",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Вот. Это честнее коробок. Пол — тоже мебель, если на нём сидим мы.",
    next: "rent5",
  },
  {
    id: "rent5",
    speaker: "n",
    ira: "tender",
    sasha: null,
    bg: "home",
    music: "home",
    text: "Потом — своя, в Нижнем. Не идеальная. Своя. Утром ключи лежали в миске, как будто так было всегда. Рядом — карточка Тепслы: машина тоже прописалась.",
    next: "house1",
  },
  {
    id: "house1",
    speaker: "n",
    bg: "novoselye",
    ira: null,
    sasha: null,
    cg: "novoselye",
    music: "home",
    ambience: "home",
    text: "Новоселье вам к лицу — так было написано на стекле. Мы ещё не внесли диван, а уже стояли в дверях двумя парами ног. Дом начался с порога.",
    next: "house2",
  },
  {
    id: "house2",
    speaker: "ira",
    cg: "novoselye",
    text: "Пусть витрина врёт. Нам к лицу.",
    next: "house3",
  },
  {
    id: "house3",
    speaker: "n",
    cg: "novoselye",
    text: "За стеклом — чужой свет. С этой стороны — наши кроссовки. Этого хватило, чтобы сказать: мы въехали.",
    next: "alf1",
  },
  {
    id: "alf1",
    speaker: "n",
    bg: "home",
    ira: null,
    sasha: null,
    cg: "cg-alf",
    music: "home",
    ambience: "home",
    text: "В новой квартире нас уже ждал тот, кто договор не подписывал. Альф. Лысый, тёплый, с характером режиссёра. Нижний — его город. Других городов он не признаёт.",
    next: "alf2",
  },
  {
    id: "alf2",
    speaker: "ira",
    cg: "cg-alf",
    text: "Он разрешил нам жить. Это важнее ключей.",
    next: "alf3",
  },
  {
    id: "alf3",
    speaker: "n",
    cg: "cg-alf",
    text: "Сфинкс смотрел так, будто проверял, годимся ли мы в хозяева. Мы не спорили.",
    choices: [
      { text: "Почесать за ухом — если позволит", next: "alf4a", warmth: 1 },
      { text: "Отдать ему диван без боя", next: "alf4b", warmth: 2 },
      { text: "«Теперь нас трое. И этого хватит на одну кухню.»", next: "alf4c", warmth: 1 },
    ],
  },
  {
    id: "alf4a",
    speaker: "n",
    cg: "cg-alf",
    text: "Позволил. Кожа была тёплая, как ладонь. Альф зажмурился — коротко, по-хозяйски, и это было «да».",
    next: "rent6",
  },
  {
    id: "alf4b",
    speaker: "ira",
    cg: "cg-alf",
    text: "Правильно. В этой квартире диван принадлежит Альфу. Мы — гости с правом на чай.",
    next: "rent6",
  },
  {
    id: "alf4c",
    speaker: "ira",
    cg: "cg-alf",
    text: "Он это уже решил. Диму не видел и не увидит: Барановичи далеко, а диван — здесь. Им не обязательно знакомиться, чтобы оба были своими.",
    next: "rent6",
  },
  {
    id: "rent6",
    speaker: "sasha",
    sasha: "warm",
    ira: "smile",
    cg: null,
    text: "Слышишь? Теперь это точно мы. Даже если гремим. Даже если за окном Нижний, а не открытка.",
    next: "ch6",
  },

  {
    id: "ch6",
    speaker: "n",
    bg: "kitchen",
    ira: null,
    sasha: null,
    cg: null,
    music: "home",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "VII", title: "Дима", hint: "ему десять" },
    text: "",
    next: "dima1",
  },
  {
    id: "dima1",
    speaker: "n",
    bg: "kitchen",
    ira: "thoughtful",
    sasha: null,
    music: "quiet",
    ambience: "home",
    text: "Дима живёт в Барановичах. Ему десять. Родные — в Минске, мы — в Нижнем. В этом городе из наших — только он. Альфа мы не взяли. Я боялся этого дня больше, чем анкеты и договора вместе.",
    next: "dima2",
  },
  {
    id: "dima2",
    speaker: "ira",
    ira: "tender",
    text: "Саша. Я еду к нему. Не к родным, не «вообще в Беларусь». К Диме. Ему десять — это уже человек, не объяснение.",
    next: "dima3",
  },
  {
    id: "dima3",
    speaker: "n",
    ira: "smile",
    text: "Стол в Барановичах был накрыт на троих. Без родных — они в Минске. Печенье чуть кривое — моё. Третья чашка меньше двух других и от этого важнее.",
    next: "dima4",
  },
  {
    id: "dima4",
    speaker: "n",
    ira: "smile",
    text: "Он смотрел на неё внимательно, как смотрят на новую погоду: хорошая или нет.",
    choices: [
      { text: "«Дима, это Ира. Она мне очень важна.»", next: "dima5a", warmth: 1 },
      { text: "Не представлять. Дать им самим.", next: "dima5b", warmth: 2 },
      { text: "«Это мой человек. Можно, она будет иногда с нами.»", next: "dima5c", warmth: 1 },
    ],
  },
  {
    id: "dima5a",
    speaker: "n",
    ira: "shy",
    text: "Я сказал это проще, чем думал. Дима кивнул — так кивают, когда решают дать шанс.",
    next: "dima6",
  },
  {
    id: "dima5b",
    speaker: "n",
    ira: "smile",
    text: "Ира не сюсюкала и не играла в «подругу папы». Просто села. Спросила про школу так, будто ответ ей правда нужен.",
    next: "dima6",
  },
  {
    id: "dima5c",
    speaker: "n",
    ira: "tender",
    text: "«Мой человек» прозвучало громче, чем я хотел. Дима посмотрел на меня, потом на неё — и кивнул серьёзнее своих десяти.",
    next: "dima6",
  },
  {
    id: "dima6",
    speaker: "n",
    ira: "tender",
    text: "Потом, уже у двери, как будто между делом, он спросил: «А вы будете ещё приходить?»",
    next: "dima7",
  },
  {
    id: "dima7",
    speaker: "ira",
    ira: "shy",
    text: "Если можно.",
    next: "dima8",
  },
  {
    id: "dima8",
    speaker: "n",
    ira: "tender",
    sasha: "warm",
    text: "Можно было. Оказалось — можно было давно.",
    next: "ch7",
  },

  {
    id: "ch7",
    speaker: "n",
    bg: "palace",
    ira: null,
    sasha: null,
    cg: null,
    music: "warm",
    ambience: "none",
    ui: "chapter",
    chapter: { n: "VIII", title: "Минск", hint: "родные, потом сын" },
    text: "",
    next: "msk1",
  },
  {
    id: "msk1",
    speaker: "n",
    bg: "palace",
    ira: "smile",
    sasha: null,
    music: "warm",
    ambience: "none",
    text: "Из Нижнего в Минск мы ездили дважды. Первый раз площадь была слишком большой для двоих — и всё равно мы влезли.",
    next: "msk2",
  },
  {
    id: "msk2",
    speaker: "ira",
    ira: "laugh",
    text: "Сначала площадь. Потом твои родные — они здесь, в Минске. Дима в другом городе, ему десять. География у нас не простая. Зато честная.",
    next: "msk3",
  },
  {
    id: "msk3",
    speaker: "n",
    ira: "smile",
    text: "Катались по Минску, как люди, которым ещё можно притворяться туристами. Потом притворство кончилось: сначала к родным. Потом — дорога в Барановичи, к Диме. Только к нему.",
    choices: [
      { text: "Сначала к родным в Минске", next: "msk4a", warmth: 1 },
      { text: "Сначала в Барановичи, к Диме", next: "msk4b", warmth: 2 },
      { text: "Ещё один круг по городу — и к родным", next: "msk4c", warmth: 1 },
    ],
  },
  {
    id: "msk4a",
    speaker: "n",
    bg: "relatives",
    ira: "shy",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "За столом у родных в Минске стоял лишний стул, который вдруг перестал быть лишним. Чай, варенье, вопросы, которые задают не из злости — из любви, которая не умеет шептать. Димы за этим столом не было: он в Барановичах. Ему десять, и это другой визит.",
    next: "msk5",
  },
  {
    id: "msk4b",
    speaker: "n",
    bg: "kitchen",
    ira: "tender",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "В Барановичах — только Дима. Десять лет, дверь открыл быстрее, чем я успел придумать речь. На Иру смотрел уже не как на погоду. Как на человека, который держит слово: приезжает. Без родных. Без Альфа. Просто он.",
    next: "msk5",
  },
  {
    id: "msk4c",
    speaker: "n",
    bg: "sunset",
    ira: "smile",
    sasha: null,
    music: "warm",
    ambience: "none",
    text: "Минск в закате делал вид, что знает нас давно. Это была ложь, и очень удобная. Родные ждали в этом же городе. Барановичи — завтра, или после чая, если честно.",
    next: "msk5",
  },
  {
    id: "msk5",
    speaker: "n",
    bg: "relatives",
    ira: "smile",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "Родные накрыли на всех. Димы за столом не было — и не должно было: он не «часть Минска», он сам. Альф тем более остался в Нижнем.",
    next: "msk6",
  },
  {
    id: "msk6",
    speaker: "ira",
    ira: "tender",
    text: "Мне тут не страшно. Скажи им это как-нибудь вечером, когда я уже не услышу. Или не говори. Я и так вижу.",
    next: "msk7",
  },
  {
    id: "msk7",
    speaker: "n",
    bg: "palace",
    ira: "laugh",
    sasha: "warm",
    music: "warm",
    ambience: "none",
    text: "Второй раз Минск уже не спрашивал, кто мы. Площадь была та же. Родные накрывали, не уточняя. Потом снова Барановичи — только Дима, десять лет, и фраза «опять вы», которая прозвучала как приглашение.",
    next: "msk8",
  },
  {
    id: "msk8",
    speaker: "sasha",
    sasha: "warm",
    ira: "smile",
    text: "Два раза. Минск — родные. Барановичи — сын. Беларусь ещё и Тепсла: её купили там. Нижний — кот, который в Беларусь не ездит.",
    next: "ch8",
  },

  {
    id: "ch8",
    speaker: "n",
    bg: "future",
    ira: null,
    sasha: null,
    cg: null,
    music: "quiet",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "IX", title: "Наш", hint: "ещё один человек" },
    text: "",
    next: "want1",
  },
  {
    id: "want1",
    speaker: "n",
    bg: "future",
    ira: "thoughtful",
    sasha: null,
    music: "quiet",
    ambience: "home",
    text: "Дома, в Нижнем, Альф спал клубком. Дима был в Барановичах. Между городами стало тихо так, что было слышно будущее.",
    next: "want2",
  },
  {
    id: "want2",
    speaker: "ira",
    ira: "tender",
    text: "Саша. Я не про завтра утром. Я про нашего. Если ты тоже.",
    next: "want3",
  },
  {
    id: "want3",
    speaker: "n",
    ira: "tender",
    text: "Она не ставила это как условие. Говорила так, как тогда в чате: без плана, и от этого честнее.",
    choices: [
      { text: "«Тоже.»", next: "want4a", warmth: 2 },
      { text: "«Мне страшно. И очень хочется.»", next: "want4b", warmth: 2 },
      { text: "«Дима от этого не станет меньше. Это важно сказать.»", next: "want4c", warmth: 1 },
    ],
  },
  {
    id: "want4a",
    speaker: "sasha",
    sasha: "warm",
    ira: "shy",
    text: "Тоже. Я думал, что это слово надо заслужить дольше. Оказалось — его надо просто не испугать.",
    next: "want5",
  },
  {
    id: "want4b",
    speaker: "ira",
    ira: "laugh",
    sasha: "awkward",
    text: "Страшно — это честно. Хочется — это мы. Остальное придумаем, как кофейню и договор.",
    next: "want5",
  },
  {
    id: "want4c",
    speaker: "ira",
    ira: "tender",
    sasha: "warm",
    text: "Не станет. Он первый. Наш будет не вместо. Рядом.",
    next: "want5",
  },
  {
    id: "want5",
    speaker: "n",
    ira: "tender",
    sasha: null,
    bg: "future",
    text: "На столе стояли две кружки. Между ними было пустое место — ещё не человек, уже не воздух.",
    next: "want6",
  },
  {
    id: "want6",
    speaker: "ira",
    ira: "smile",
    text: "Не надо обещать дату. Надо обещать, что мы не будем делать вид, будто этого не хотим.",
    next: "fin1",
  },

  {
    id: "fin1",
    speaker: "n",
    bg: "sunset",
    ira: null,
    sasha: null,
    cg: null,
    music: "warm",
    ambience: "none",
    text: "Приложение. Кофейня. Лист бумаги. Поло. Тепслу купили в Беларуси — каламбур оставили себе. Альф в Нижнем. Родные в Минске. Дима, десять лет, в Барановичах. И слово «наш», которое ещё впереди.",
    next: "fin2",
  },
  {
    id: "fin2",
    speaker: "n",
    bg: "title",
    music: "title",
    ambience: "snow",
    text: "А снег, если честно, так и не кончился. Просто в нём уже было место ещё для одного человека.",
    ending: "together",
  },

  {
    id: "numbers1",
    speaker: "n",
    bg: "street",
    ira: "smile",
    sasha: null,
    music: "snow",
    ambience: "snow",
    cg: null,
    text: "На улице снег стал мельче. Мы остановились под козырьком, как два человека, которые ещё не имеют права на долгие прощания.",
    next: "numbers2",
  },
  {
    id: "numbers2",
    speaker: "ira",
    ira: "tender",
    text: "Напишите. Не завтра утром, ладно? Завтра утром все герои становятся осторожными. Напишите вечером.",
    next: "numbers3",
  },
  {
    id: "numbers3",
    speaker: "sasha",
    sasha: "warm",
    text: "Вечером. Пока снег ещё помнит нас.",
    next: "numbers4",
  },
  {
    id: "numbers4",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "title",
    text: "Она ушла первой. Свитер мелькнул в жёлтом окне такси. В кармане лежал номер — тёплый, как невыпитая чашка.",
    ending: "numbers",
  },

  {
    id: "almost1",
    speaker: "n",
    bg: "cafe-brick",
    ira: "thoughtful",
    music: "quiet",
    ambience: "cafe",
    cg: null,
    text: "Мы попрощались вежливо, как умеют взрослые, когда боятся назвать вечер важным.",
    next: "almost2",
  },
  {
    id: "almost2",
    speaker: "n",
    ira: null,
    bg: "street",
    ambience: "snow",
    text: "Уже на улице я нашёл в кармане пальто закладку. На ней было одно слово её почерком: «Ещё».",
    next: "almost3",
  },
  {
    id: "almost3",
    speaker: "n",
    bg: "title",
    text: "Не номер. Не адрес. Просто «ещё». Иногда этого хватает, чтобы вернуться в ту же кофейню через неделю.",
    ending: "almost",
  },
];

export const STORY: Record<string, StoryNode> = Object.fromEntries(nodes.map((n) => [n.id, n]));
export const START_ID = "ch1";

export function resolveRoute(warmth: number): string {
  if (warmth >= 7) return "together1";
  if (warmth >= 4) return "numbers1";
  return "almost1";
}

export const CHAPTERS: {
  id: string;
  n: string;
  title: string;
  hint: string;
  need?: string;
  warmth?: number;
}[] = [
  { id: "ch1", n: "I", title: "МЭТЧ", hint: "приложение" },
  { id: "ch2", n: "II", title: "Кофейня", hint: "первый вечер" },
  { id: "ch3", n: "III", title: "Договор", hint: "две недели спустя", need: "together", warmth: 8 },
  { id: "chDrive", n: "IV", title: "За рулём", hint: "Поло, потом Тепсла", need: "together", warmth: 8 },
  { id: "ch4", n: "V", title: "Полгода", hint: "как во сне", need: "together", warmth: 8 },
  { id: "ch5", n: "VI", title: "Дом", hint: "новоселье", need: "together", warmth: 8 },
  { id: "ch6", n: "VII", title: "Дима", hint: "ему десять", need: "together", warmth: 8 },
  { id: "ch7", n: "VIII", title: "Минск", hint: "родные, потом сын", need: "together", warmth: 8 },
  { id: "ch8", n: "IX", title: "Наш", hint: "ещё один человек", need: "together", warmth: 8 },
];

export const ENDING_TITLE: Record<string, string> = {
  together: "Наша история",
  numbers: "Вечером",
  almost: "Ещё",
  missed: "Стекло",
};

export const ENDING_BLURB: Record<string, string> = {
  together: "Тепслу купили в Беларуси. Альф в Нижнем. Родные в Минске. Дима, десять, в Барановичах.",
  numbers: "Номер в кармане. Вечер не закрыт, только поставлен на паузу.",
  almost: "Закладка с одним словом. Иногда этого достаточно.",
  missed: "Вы не сели. История осталась тёплым окном.",
};
