import type { StoryNode } from "./types";

const nodes: StoryNode[] = [
  {
    id: "ch1",
    speaker: "n",
    bg: "night",
    ira: null,
    sasha: null,
    cg: null,
    music: "quiet",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "I", title: "МЭТЧ", hint: "сначала был чат" },
    text: "",
    next: "app1",
  },
  {
    id: "app1",
    speaker: "n",
    bg: "night",
    music: "quiet",
    ambience: "home",
    text: "Вечер был слишком обычный, чтобы ждать от него сюжет. Я листал анкеты большим пальцем — тем жестом, в котором нет ни надежды, ни гордости.",
    next: "app2",
  },
  {
    id: "app2",
    speaker: "n",
    text: "Ира. На фото она смеялась не в камеру, а кому-то, кого не было в кадре. В тексте — коротко, без девиза. Я написал первым, потому что иначе не написал бы никогда.",
    next: "app3",
  },
  {
    id: "app3",
    speaker: "n",
    ui: "chat",
    text: "Ответ пришёл быстрее, чем я успел спрятать телефон.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
    ],
    choices: [
      { text: "«Второе: у вас смех на фото не для анкеты.»", next: "app4a", warmth: 2 },
      { text: "«Второе: куда идут, когда снег ведёт себя слишком серьёзно?»", next: "app4b", warmth: 2 },
      { text: "«Второе: просто здравствуйте. Без плана.»", next: "app4c", warmth: 1 },
    ],
  },
  {
    id: "app4a",
    speaker: "n",
    ui: "chat",
    text: "Она ответила сразу. Без смайлика-щита.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: у вас смех на фото не для анкеты." },
      { from: "ira", text: "Жизнь — анкета, только без кнопки «скрыть». Но спасибо. Это почти комплимент." },
    ],
    next: "app5",
  },
  {
    id: "app4b",
    speaker: "n",
    ui: "chat",
    text: "Она, кажется, ждала именно этот вопрос.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: куда идут, когда снег ведёт себя слишком серьёзно?" },
      { from: "ira", text: "В кофейню у угла. Жёлтый свет, на вывеске от холода половина букв. Я там часто бываю с тетрадью." },
    ],
    next: "app5",
  },
  {
    id: "app4c",
    speaker: "n",
    ui: "chat",
    text: "Без плана оказалось правильной стратегией.",
    chat: [
      { from: "sasha", text: "Привет. Если честно, я не умею писать первое сообщение." },
      { from: "ira", text: "Тогда не пишите первое. Пишите второе. Я уже тут." },
      { from: "sasha", text: "Второе: просто здравствуйте. Без плана." },
      { from: "ira", text: "Без плана — это уже план. Мне нравится." },
    ],
    next: "app5",
  },
  {
    id: "app5",
    speaker: "n",
    ui: "chat",
    text: "Дальше писалось само. Не остроумно напоказ — скорее как два человека, которые узнали друг друга раньше, чем успели представиться.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
    ],
    choices: [
      { text: "«Да. Кофейня у угла, после восьми?»", next: "app6", warmth: 2 },
      { text: "«Да. Только я могу оказаться скучнее анкеты.»", next: "app6b", warmth: 1 },
      { text: "«Можно подумать до завтра.»", next: "app6c" },
    ],
  },
  {
    id: "app6",
    speaker: "n",
    ui: "chat",
    text: "Общее нашлось сразу. Его не пришлось добывать.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Да. Кофейня у угла, после восьми?" },
      { from: "ira", text: "Угла хватит. Восьми хватит. Если будете мокрым от снега — я не обижусь." },
    ],
    next: "app7",
  },
  {
    id: "app6b",
    speaker: "n",
    ui: "chat",
    text: "Общее нашлось сразу. Его не пришлось добывать.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Да. Только я могу оказаться скучнее анкеты." },
      { from: "ira", text: "Анкета всегда врёт в одну сторону. Приходите. Разберёмся на месте." },
    ],
    next: "app7",
  },
  {
    id: "app6c",
    speaker: "n",
    ui: "chat",
    text: "Я написал «подумать». Она написала так, что думать стало незачем.",
    chat: [
      { from: "ira", text: "Слушайте. Давайте не растягивать это на три недели переписок. Кофе существует." },
      { from: "sasha", text: "Можно подумать до завтра." },
      { from: "ira", text: "Можно. А можно просто прийти. Кофейня у угла, после восьми. Я буду с тетрадью — чтобы было куда смотреть, если вдруг страшно." },
    ],
    next: "app7",
  },
  {
    id: "app7",
    speaker: "n",
    ui: undefined,
    chat: undefined,
    text: "Мы ещё не видели друг друга. А вайб уже сидел между сообщениями — как третий собеседник, которому не нужно представиться.",
    next: "ch2",
  },
  {
    id: "ch2",
    speaker: "n",
    bg: "street",
    ira: null,
    sasha: null,
    cg: null,
    music: "snow",
    ambience: "snow",
    ui: "chapter",
    chapter: { n: "II", title: "Кофейня", hint: "первый вечер" },
    text: "",
    next: "s1",
  },
  {
    id: "s1",
    speaker: "n",
    bg: "street",
    ira: null,
    sasha: null,
    cg: null,
    music: "snow",
    ambience: "snow",
    text: "Снег шёл уже третий час. Не открыточный — мокрый, тяжёлый, такой, от которого пальто становится на килограмм тяжелее, а мысли — короче.",
    next: "s2",
  },
  {
    id: "s2",
    speaker: "n",
    text: "Я шёл на свидание привычным маршрутом, как ходят на экзамен, который сам назначил. В кармане лежал телефон с чатом. В голове — все способы опоздать и все способы сбежать.",
    next: "s3",
  },
  {
    id: "s3",
    speaker: "n",
    bg: "street",
    text: "Маленькая кофейня. Жёлтый свет, мокрые стёкла, на вывеске от холода осталась только половина букв. Внутри кто-то жил обычной жизнью — и это вдруг показалось важным.",
    next: "s4",
  },
  {
    id: "s4",
    speaker: "n",
    bg: "cafe-brick",
    music: "cafe",
    ambience: "cafe",
    text: "Тёплое дерево, запах эспрессо, чужие пальто на крючках. Снег за дверью остался как чужая страна.",
    next: "s5",
  },
  {
    id: "s5",
    speaker: "n",
    ira: "thoughtful",
    text: "За столом у окна сидела женщина в кремовом свитере и что-то писала в тетради, не поднимая головы. Напротив неё — пустая чашка и пустое место. Как в сообщении.",
    next: "ask",
  },
  {
    id: "ask",
    speaker: "n",
    ira: "thoughtful",
    text: "Можно было сказать имя. Можно было постоять. Можно было сделать вид, что перепутал кофейню.",
    choices: [
      { text: "«Ира?»", next: "sit1", warmth: 1 },
      { text: "Постоять у стойки. Вдруг это не она.", next: "bar1" },
      { text: "Развернуться. Ещё не поздно.", next: "leave1" },
    ],
  },

  {
    id: "leave1",
    speaker: "n",
    ira: null,
    bg: "street",
    music: "quiet",
    ambience: "snow",
    text: "Дверь закрылась за спиной мягко, как чужая книга. Снег сразу вернул меня себе.",
    next: "leave2",
  },
  {
    id: "leave2",
    speaker: "n",
    text: "Через стекло я ещё секунду видел кремовый свитер и наклонённую голову. Потом окно запотело — и история, которой не случилось, стала просто тёплым пятном в холоде.",
    next: "leave3",
  },
  {
    id: "leave3",
    speaker: "n",
    text: "Иногда знакомство начинается с того, что ты не заходишь. Это тоже выбор. Просто очень тихий.",
    ending: "missed",
  },

  {
    id: "bar1",
    speaker: "n",
    ira: "thoughtful",
    text: "Я встал у стойки, сделал вид, что изучаю меню, которое знал наизусть с прошлого месяца. Она писала ещё с минуту, потом подняла глаза.",
    next: "bar2",
  },
  {
    id: "bar2",
    speaker: "ira",
    ira: "smile",
    text: "Саша? Я вас почти не узнала в снегу. Тут свободно. Я вас и ждала — только тетрадь не двигайте.",
    next: "bar3",
  },
  {
    id: "bar3",
    speaker: "sasha",
    sasha: "awkward",
    text: "Тетрадь не трону. Насчёт снега — он меня немного переиграл по пути.",
    next: "sit2",
  },

  {
    id: "sit1",
    speaker: "ira",
    ira: "smile",
    text: "Я. А вы — мокрый Саша из приложения. Садитесь. Только не двигайте тетрадь — там держится вся моя сегодняшняя дисциплина.",
    next: "sit2",
  },
  {
    id: "sit2",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "cafe",
    text: "Я сел. Между нами лежала тетрадь, две чашки на цветочных блюдцах и то странное молчание, в котором ещё ничего нельзя испортить.",
    next: "sit3",
  },
  {
    id: "sit3",
    speaker: "ira",
    ira: "smile",
    text: "Ира. Живая. Если вдруг решите обращаться по имени, а не «девушка из чата».",
    next: "sit4",
  },
  {
    id: "sit4",
    speaker: "sasha",
    sasha: "smile",
    text: "Саша. Девушка из чата тоже хорошо звучит, но Ира — лучше.",
    next: "sit5",
  },
  {
    id: "sit5",
    speaker: "ira",
    ira: "laugh",
    sasha: null,
    text: "Тогда Саша. Вы всегда приходите, когда снег начинает себя слишком серьёзно вести, или это я так удачно написала про кофейню?",
    next: "open",
  },
  {
    id: "open",
    speaker: "n",
    ira: "smile",
    text: "Официант уже шёл. Оставалось решить, с чего начинается разговор у людей, которые уже здоровались пальцами.",
    choices: [
      { text: "«Что пишете?»", next: "write1", warmth: 2 },
      { text: "«Снег сегодня какой-то личный.»", next: "snowtalk1", warmth: 1 },
      { text: "Просто заказать кофе и помолчать", next: "quiet1" },
    ],
  },

  {
    id: "write1",
    speaker: "ira",
    ira: "thoughtful",
    text: "Письма, которые не отправлю. Иногда списки. Сегодня — список причин не идти домой сразу.",
    next: "write2",
  },
  {
    id: "write2",
    speaker: "sasha",
    sasha: "awkward",
    text: "И как, список работает?",
    next: "write3",
  },
  {
    id: "write3",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Пока вы сели — да. Это уже пункт.",
    next: "merge1",
  },

  {
    id: "snowtalk1",
    speaker: "ira",
    ira: "laugh",
    text: "Личный снег. Запомню. У меня сапоги уже написали заявление об увольнении.",
    next: "snowtalk2",
  },
  {
    id: "snowtalk2",
    speaker: "sasha",
    sasha: "laugh",
    text: "Моё пальто тоже требует переговоров. Я шёл якобы на минуту. Из чата это звучало смелее.",
    next: "snowtalk3",
  },
  {
    id: "snowtalk3",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Минуты в такую погоду врут. Это их профессия.",
    next: "merge1",
  },

  {
    id: "quiet1",
    speaker: "n",
    ira: "thoughtful",
    text: "Мы пили молча. Снег царапал стекло. Это не было неловко — скорее как два человека, которые уже знакомы наполовину.",
    next: "quiet2",
  },
  {
    id: "quiet2",
    speaker: "ira",
    ira: "smile",
    text: "Вы всегда такой молчаливый, или это снег на вас так действует?",
    next: "quiet3",
  },
  {
    id: "quiet3",
    speaker: "sasha",
    sasha: "awkward",
    text: "Снег. И ещё я не хотел спугнуть человека с тетрадью. В чате вы казались спокойнее. Вживую — серьёзнее.",
    next: "merge1",
  },

  {
    id: "merge1",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "cafe",
    text: "Принесли кофе. У неё — без сахара. У меня — с сахаром, хотя я всегда говорю, что «почти не кладу».",
    next: "merge2",
  },
  {
    id: "merge2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Забавно. Люди на первых встречах либо становятся честнее, либо начинают рассказывать биографию. Вы какой?",
    next: "bio",
  },
  {
    id: "bio",
    speaker: "n",
    text: "Честность в восемь вечера — скользкая вещь. Но стол был маленький, и врать за ним было бы странно.",
    choices: [
      { text: "«Шёл на свидание. Честно. Немного боюсь.»", next: "honest1", warmth: 1 },
      { text: "«Ищу укрытие от судьбы. Пока только от снега.»", next: "joke1", warmth: 2 },
      { text: "«Работа рядом. Тут кофе лучше, чем в офисе.»", next: "work1" },
    ],
  },

  {
    id: "honest1",
    speaker: "ira",
    ira: "tender",
    text: "Хороший ответ. Я тоже не планировала никого знакомить так быстро. Просто рука замёрзла, и тетрадь сама открылась.",
    next: "deep1",
  },
  {
    id: "joke1",
    speaker: "ira",
    ira: "laugh",
    text: "От судьбы это заведение слабовато. От снега — вполне. Садитесь удобнее, раз уж укрылись.",
    next: "deep1",
  },
  {
    id: "work1",
    speaker: "ira",
    ira: "smile",
    text: "Офисный кофе — отдельный вид жестокости. Я вас понимаю.",
    next: "deep1",
  },

  {
    id: "deep1",
    speaker: "n",
    ira: "thoughtful",
    sasha: null,
    text: "За окном фонарь тонул в белом. Казалось, город уменьшился до этого стола — и это было не страшно.",
    next: "deep2",
  },
  {
    id: "deep2",
    speaker: "ira",
    ira: "smile",
    text: "Знаете, что мне нравится в первых встречах? Можно сказать правду: анкета уже соврала за нас всё лишнее.",
    next: "deep3",
  },
  {
    id: "deep3",
    speaker: "n",
    text: "Она крутила ложку. Свитер чуть съехал с плеча, и она поправила его так, будто это тоже было частью мысли.",
    choices: [
      { text: "«Тогда давайте правду. Что вы делаете в этом городе?»", next: "city1", warmth: 1 },
      { text: "«А если снег не кончится до весны?»", next: "if1", warmth: 2 },
      { text: "«Вы смеётесь так, будто уже решили, что я не страшный.»", next: "flirt1", warmth: 1 },
    ],
  },

  {
    id: "city1",
    speaker: "ira",
    ira: "thoughtful",
    text: "Живу. Работаю. Иногда убегаю в такие места, где можно писать и не объяснять, зачем. А вы?",
    next: "city2",
  },
  {
    id: "city2",
    speaker: "sasha",
    sasha: "warm",
    text: "Похоже. Только вместо тетради у меня обычно экран. Сегодня экран проиграл окну.",
    next: "phone1",
  },

  {
    id: "if1",
    speaker: "ira",
    ira: "surprise",
    text: "Тогда придётся научиться танцевать в сапогах. Или переехать в эту кофейню совсем.",
    next: "if2",
  },
  {
    id: "if2",
    speaker: "sasha",
    sasha: "laugh",
    text: "Я бронирую стол у окна. Вы — тетрадь. Справедливо.",
    next: "if3",
  },
  {
    id: "if3",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Справедливо. И немного опасно: так начинаются привычки.",
    next: "phone1",
  },

  {
    id: "flirt1",
    speaker: "ira",
    ira: "shy",
    text: "Я ещё не решила. Но пальто у вас честное, а это уже что-то.",
    next: "flirt2",
  },
  {
    id: "flirt2",
    speaker: "sasha",
    sasha: "awkward",
    text: "Пальто будет польщено. Оно редко получает комплименты.",
    next: "phone1",
  },

  {
    id: "phone1",
    speaker: "n",
    ira: "surprise",
    sasha: null,
    text: "Телефон на столе коротко вспыхнул. Ира взглянула на экран, и на секунду стала человеком с другой жизнью — той, что была до этого стола.",
    next: "phone2",
  },
  {
    id: "phone2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Друзья. «Ты ещё придёшь?» Я обещала заехать. Но снег… и кофе… и вы тут сидите, как пункт из списка.",
    next: "stay",
  },
  {
    id: "stay",
    speaker: "n",
    ira: "thoughtful",
    text: "Можно было отпустить. Можно было попросить остаться. Между этими двумя фразами обычно и живёт вечер.",
    choices: [
      { text: "«Останься. Снег всё равно не кончится.»", next: "stayyes", warmth: 2 },
      { text: "«Могу проводить, если решите идти.»", next: "walkoffer", warmth: 1 },
      { text: "«Если надо — идите. Я не держу.»", next: "release1" },
    ],
  },

  {
    id: "stayyes",
    speaker: "ira",
    ira: "tender",
    text: "Напишу, что сугробы взяли меня в заложники. Это почти правда.",
    next: "after1",
  },
  {
    id: "walkoffer",
    speaker: "ira",
    ira: "smile",
    text: "Проводить — это уже не «случайно сели». Это уже маршрут.",
    next: "after1",
  },
  {
    id: "release1",
    speaker: "ira",
    ira: "smile",
    text: "Вежливый Саша. Хорошо. Тогда я останусь ещё на одну чашку — уже не из вежливости.",
    next: "after1",
  },

  {
    id: "after1",
    speaker: "n",
    ira: "smile",
    bg: "cafe",
    music: "cafe",
    text: "Вторая чашка пришла сама, без заказа, как будто кофейня тоже поняла, что вечер не окончен.",
    next: "after2",
  },
  {
    id: "after2",
    speaker: "ira",
    ira: "laugh",
    text: "Расскажите что-нибудь ненужное. Не резюме. Например, какой у вас любимый бесполезный навык.",
    next: "skill",
  },
  {
    id: "skill",
    speaker: "n",
    text: "Ненужное — самое нужное в знакомстве.",
    choices: [
      { text: "«Умею угадывать, когда кто-то хочет ещё кофе.»", next: "skill1", warmth: 1 },
      { text: "«Запоминаю песни из чужих наушников в метро.»", next: "skill2", warmth: 2 },
      { text: "«Серьёзно делать вид, что разбираюсь в винах.»", next: "skill3", warmth: 1 },
    ],
  },
  {
    id: "skill1",
    speaker: "ira",
    ira: "smile",
    text: "Опасный навык. Я как раз хотела. Вы маг или просто внимательный?",
    next: "close1",
  },
  {
    id: "skill2",
    speaker: "ira",
    ira: "tender",
    text: "Это красиво и немного грустно. Как коллекция жизней, которые вам не принадлежат.",
    next: "close1",
  },
  {
    id: "skill3",
    speaker: "ira",
    ira: "laugh",
    text: "«Нотки леса и лёгкое разочарование». Я так тоже умею.",
    next: "close1",
  },

  {
    id: "close1",
    speaker: "n",
    ira: "smile",
    text: "Снег за окном стал реже, будто выдохнул. Кофейня поредела. Остались те, кому некуда спешить, и те, кто делает вид, что некуда спешить.",
    next: "close2",
  },
  {
    id: "close2",
    speaker: "ira",
    ira: "thoughtful",
    text: "Скоро закроют. Можно разойтись, как приличные взрослые. Можно ещё немного украсть у погоды.",
    next: "fork",
  },
  {
    id: "fork",
    speaker: "n",
    ira: "smile",
    text: "Вечер стоял на развилке — тонкой, как след на снегу.",
    choices: [
      { text: "«Прогуляемся? Пока снег не передумал.»", next: "park1", warmth: 2 },
      { text: "«Сидим, пока нас не выгонят.»", next: "late1", warmth: 1 },
      { text: "«Давайте хотя бы обменяемся номерами.»", next: "num1" },
    ],
  },

  {
    id: "park1",
    speaker: "n",
    bg: "park",
    ira: "smile",
    sasha: null,
    music: "snow",
    ambience: "snow",
    text: "Парк был белым и пустым. Берёзы стояли как люди, которые тоже не знали, куда деть руки. Скамейка тонула в сугробе по пояс.",
    next: "park2",
  },
  {
    id: "park2",
    speaker: "ira",
    ira: "laugh",
    text: "Если мы сейчас упадём в сугроб, это будет очень литературно и очень мокро.",
    next: "park3",
  },
  {
    id: "park3",
    speaker: "n",
    ira: "smile",
    text: "Она шла рядом, иногда задевая рукавом. Снег падал ей в волосы и сразу становился своим.",
    choices: [
      { text: "Предложить руку, когда она поскальзывается", next: "hand1", warmth: 2 },
      { text: "«Можно я расскажу, что боялся сюда зайти?»", next: "fear1", warmth: 1 },
      { text: "Идти молча и просто быть рядом", next: "silent1", warmth: 1 },
    ],
  },
  {
    id: "hand1",
    speaker: "n",
    ira: "shy",
    text: "Её пальцы были холодными, и она не отобрала руку сразу — только посмотрела так, будто проверяла, не испугаюсь ли я собственной смелости.",
    next: "hand2",
  },
  {
    id: "hand2",
    speaker: "ira",
    ira: "tender",
    text: "Тёплая ладонь в такой снег — это уже почти признание. Не пугайтесь, я преувеличиваю. Немного.",
    next: "endgate",
  },
  {
    id: "fear1",
    speaker: "sasha",
    sasha: "awkward",
    text: "Я почти ушёл. Подумал, что мешаю человеку с тетрадью. Хорошо, что не ушёл.",
    next: "fear2",
  },
  {
    id: "fear2",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Хорошо. Я тоже почти написала «занято» на лице. Не написала.",
    next: "endgate",
  },
  {
    id: "silent1",
    speaker: "n",
    ira: "tender",
    text: "Молчание оказалось удобным, как шарф. Иногда знакомство — это просто два человека, которые не торопят тишину.",
    next: "endgate",
  },

  {
    id: "late1",
    speaker: "n",
    bg: "cg-cafe",
    ira: null,
    sasha: null,
    cg: "cg-cafe",
    music: "warm",
    ambience: "cafe",
    text: "Нас не выгнали сразу. Лампа над столом сделала из нас двух людей, которые уже выглядят как «мы», если не присматриваться.",
    next: "late2",
  },
  {
    id: "late2",
    speaker: "ira",
    cg: "cg-cafe",
    text: "Если завтра утром я решу, что вам это приснилось — не верьте. Я была. Вы были. Кофе был слишком сладкий, это ваша вина.",
    next: "endgate",
  },

  {
    id: "num1",
    speaker: "ira",
    ira: "smile",
    bg: "cafe-brick",
    cg: null,
    text: "Номер — это обещание без даты. Я люблю такие: они не давят и не исчезают.",
    next: "num2",
  },
  {
    id: "num2",
    speaker: "n",
    ira: "tender",
    text: "Мы обменялись телефонами на обороте её страницы. Почерк и правда был серьёзный.",
    next: "endgate",
  },

  {
    id: "endgate",
    speaker: "n",
    cg: null,
    text: "Ночь решила за нас остальное.",
    next: "route",
  },
  {
    id: "route",
    speaker: "n",
    text: "",
    next: "together1",
  },

  {
    id: "together1",
    speaker: "n",
    bg: "car",
    ira: "tender",
    sasha: "warm",
    cg: null,
    music: "warm",
    ambience: "car",
    text: "Потом была машина, тёплая до стыда после улицы. Снег колотил в стекло, как будто хотел ещё раз войти в историю.",
    next: "together2",
  },
  {
    id: "together2",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Не уезжай сразу. Посидим. Пусть дворники поработают за нас.",
    next: "together3",
  },
  {
    id: "together3",
    speaker: "n",
    ira: null,
    sasha: null,
    cg: "cg-car",
    text: "Она положила голову ему на плечо. Снег на стекле чертил карту города, который больше не имел значения.",
    next: "together4",
  },
  {
    id: "together4",
    speaker: "sasha",
    sasha: "warm",
    text: "Хорошо. Пока шёл снег — мы никуда не опаздывали.",
    next: "ch3",
  },

  {
    id: "ch3",
    speaker: "n",
    bg: "cafe-brick",
    ira: null,
    sasha: null,
    cg: null,
    music: "cafe",
    ambience: "cafe",
    ui: "chapter",
    chapter: { n: "III", title: "Договор", hint: "две недели спустя" },
    text: "",
    next: "doc1",
  },
  {
    id: "doc1",
    speaker: "n",
    bg: "cafe-brick",
    ira: "smile",
    sasha: null,
    cg: null,
    music: "cafe",
    ambience: "cafe",
    text: "Через две недели мы сидели в той же кофейне, как люди, которые уже имеют право на «наше место».",
    next: "doc2",
  },
  {
    id: "doc2",
    speaker: "ira",
    ira: "laugh",
    text: "Слушай. Давай сделаем это по-взрослому. Совсем чуть-чуть по-взрослому.",
    next: "doc3",
  },
  {
    id: "doc3",
    speaker: "sasha",
    sasha: "awkward",
    ira: "laugh",
    text: "Боюсь спрашивать.",
    next: "doc4",
  },
  {
    id: "doc4",
    speaker: "ira",
    ira: "smile",
    sasha: null,
    text: "Документ. Что мы будем парень и девушка. И будем встречаться. На бумаге — чтобы никто не слинял в «ну мы так, общаемся».",
    next: "doc5",
  },
  {
    id: "doc5",
    speaker: "n",
    ira: "smile",
    text: "Она достала из сумки нормальный лист. Не салфетку. Серьёзность была смешной — и от этого настоящей.",
    choices: [
      { text: "«Где ручка. Я готов.»", next: "docpaper", warmth: 2 },
      { text: "«Добавим пункт про кофе по воскресеньям.»", next: "docpaper", warmth: 2 },
      { text: "«Это шутка? …Хорошая. Давай.»", next: "docpaper", warmth: 1 },
    ],
  },
  {
    id: "docpaper",
    speaker: "n",
    ira: null,
    sasha: null,
    ui: "contract",
    signed: false,
    text: "На листе было мало слов. Их хватало.",
    next: "docsign",
  },
  {
    id: "docsign",
    speaker: "n",
    ui: "contract",
    signed: false,
    text: "Осталось поставить имена. Как в настоящей жизни, только честнее.",
    choices: [
      { text: "Подписать", next: "docdone", warmth: 1 },
    ],
  },
  {
    id: "docdone",
    speaker: "n",
    ui: "contract",
    signed: true,
    text: "Чернила чуть размазались. Это тоже вошло в договор.",
    next: "doc6",
  },
  {
    id: "doc6",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    ui: undefined,
    signed: undefined,
    text: "Вот. Теперь нельзя делать вид, что мы друг другу не должны хотя бы честности.",
    next: "doc7",
  },
  {
    id: "doc7",
    speaker: "sasha",
    sasha: "warm",
    ira: "tender",
    text: "Я и так не собирался.",
    next: "chDrive",
  },

  {
    id: "chDrive",
    speaker: "n",
    bg: "drive",
    ira: null,
    sasha: null,
    cg: "drive",
    music: "warm",
    ambience: "car",
    ui: "chapter",
    chapter: { n: "IV", title: "За рулём", hint: "её Поло" },
    text: "",
    next: "drive1",
  },
  {
    id: "drive1",
    speaker: "n",
    bg: "drive",
    ira: null,
    sasha: null,
    cg: "drive",
    music: "warm",
    ambience: "car",
    text: "Она приехала на работе. Фольксваген Поло, та самая, на которой утром едет по Нижнему, а вечером — за мной. Дворники мазнули по стеклу, и я понял, что пассажирское кресло уже моё.",
    next: "drive2",
  },
  {
    id: "drive2",
    speaker: "ira",
    ira: null,
    cg: "drive",
    text: "Садись. И не смотри, как я переключаю. Я это чувствую затылком.",
    next: "drive3",
  },
  {
    id: "drive3",
    speaker: "n",
    cg: "drive",
    text: "Город шёл мимо, как чужой. У неё на руле кольцо от ключей тихо стучало в такт поворотам. Я мог бы сказать, куда едем. Не сказал.",
    choices: [
      { text: "Смотреть на руки, не на дорогу", next: "drive4a", warmth: 2 },
      { text: "«Ты всегда так везёшь — как будто знаешь, где я.»", next: "drive4b", warmth: 2 },
      { text: "Включить радио и не портить тишину", next: "drive4c", warmth: 1 },
    ],
  },
  {
    id: "drive4a",
    speaker: "n",
    cg: "drive",
    text: "Пальцы спокойные. Я ловил себя на том, что завидую рулю: его держат без спроса.",
    next: "drive5",
  },
  {
    id: "drive4b",
    speaker: "ira",
    cg: "drive",
    text: "Знаю. Ты стоишь в одном и том же месте, как человек, который ещё не верит, что за ним приедут.",
    next: "drive5",
  },
  {
    id: "drive4c",
    speaker: "ira",
    cg: "drive",
    text: "Можешь не включать. Поло и так орёт за двоих, когда хочет.",
    next: "drive5",
  },
  {
    id: "drive5",
    speaker: "sasha",
    sasha: "warm",
    cg: "drive",
    text: "Тогда вези. Я пока учусь сидеть справа и не давать советов.",
    next: "chHalf",
  },

  {
    id: "chHalf",
    speaker: "n",
    bg: "home",
    ira: null,
    sasha: null,
    cg: null,
    music: "home",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "V", title: "Полгода", hint: "сначала кот" },
    text: "",
    next: "half1",
  },
  {
    id: "half1",
    speaker: "n",
    bg: "home",
    ira: "smile",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "Потом дни стали похожи друг на друга — и это вдруг перестало быть плохим. Ключ от её подъезда. Мой чай, который она пьёт неправильно. И кот, который жил тут до неё.",
    next: "half2",
  },
  {
    id: "half2",
    speaker: "n",
    bg: "home",
    ira: null,
    sasha: null,
    cg: "cg-alf",
    text: "Альф. Сфинкс. Мой. Он не встречает у двери и не изображает характер. Он просто находит колени — любые, лишь бы тёплые — и засыпает, как будто так было всегда.",
    next: "half3",
  },
  {
    id: "half3",
    speaker: "ira",
    cg: "cg-alf",
    text: "Он на мне. Это нормально? Или я теперь батарея.",
    next: "half4",
  },
  {
    id: "half4",
    speaker: "sasha",
    sasha: "warm",
    cg: "cg-alf",
    text: "Нормально. Он так всех проверяет. Если не скинул — ты свой.",
    choices: [
      { text: "Не вставать, пока он спит", next: "half5a", warmth: 2 },
      { text: "Положить ладонь ему на спину — тепло", next: "half5b", warmth: 2 },
      { text: "«Значит, ты теперь тоже его.»", next: "half5c", warmth: 1 },
    ],
  },
  {
    id: "half5a",
    speaker: "ira",
    ira: "tender",
    cg: "cg-alf",
    text: "Сиди. Нога уже отнялась. Не говори ему.",
    next: "half6",
  },
  {
    id: "half5b",
    speaker: "n",
    cg: "cg-alf",
    text: "Кожа тёплая, как изнутри кармана. Альф даже не открыл глаз. Просто стал тяжелее — это у него «оставайся».",
    next: "half6",
  },
  {
    id: "half5c",
    speaker: "ira",
    ira: "laugh",
    cg: "cg-alf",
    text: "Тогда пусть знает: батарея платная. Оплата — вот этим молчанием.",
    next: "half6",
  },
  {
    id: "half6",
    speaker: "n",
    bg: "home",
    ira: "thoughtful",
    sasha: null,
    cg: null,
    text: "Так прошло полгода. Не «как во сне». Как жизнь, в которой уже есть чужой кот на коленях. Потом я сказал то, что носил в кармане всё это время.",
    next: "half7",
  },
  {
    id: "half7",
    speaker: "sasha",
    sasha: "awkward",
    ira: "thoughtful",
    text: "Поедем в Беларусь. К Диме. Я… я не знаю, как это делается. Только что надо.",
    next: "half8",
  },
  {
    id: "half8",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Тогда едем. Не к стране. К нему.",
    next: "half9",
  },
  {
    id: "half9",
    speaker: "n",
    ira: "smile",
    text: "Альфа оставили дома. Он спал на свитере и не провожал. Ему не было дела до границ. Мне — было.",
    next: "chBy",
  },

  {
    id: "chBy",
    speaker: "n",
    bg: "kitchen",
    ira: null,
    sasha: null,
    cg: null,
    music: "quiet",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "VI", title: "Беларусь", hint: "сначала порог" },
    text: "",
    next: "by1",
  },
  {
    id: "by1",
    speaker: "n",
    bg: "kitchen",
    ira: "shy",
    sasha: null,
    music: "quiet",
    ambience: "home",
    text: "Дверь в Барановичах открылась быстрее, чем я придумал первое предложение. Дима стоял в ней — десять лет, и взгляд уже не детский. На Иру он смотрел дольше, чем на меня.",
    next: "by2",
  },
  {
    id: "by2",
    speaker: "n",
    ira: "shy",
    text: "Я хотел сказать что-то взрослое. Вышло «привет». В кухне пахло блинами, и это было громче любой речи.",
    next: "by3",
  },
  {
    id: "by3",
    speaker: "ira",
    ira: "smile",
    text: "Привет. Я Ира. Можно, я просто сяду? Без программы.",
    choices: [
      { text: "Не заполнять паузу", next: "by4a", warmth: 2 },
      { text: "«Дима. Это она.»", next: "by4b", warmth: 1 },
      { text: "Сесть тоже. Ближе к нему, не к ней — чтобы не загораживать", next: "by4c", warmth: 2 },
    ],
  },
  {
    id: "by4a",
    speaker: "n",
    ira: "thoughtful",
    text: "Минута тянулась, как тесто. Потом Дима подвинул ей тарелку. Не улыбнулся. Просто подвинул. У меня отпустило плечо, которое я держал весь поезд.",
    next: "by5",
  },
  {
    id: "by4b",
    speaker: "n",
    ira: "shy",
    text: "Слово вышло короче, чем страх. Дима кивнул — один раз, как ставят печать. Ира не полезла обниматься. Правильно.",
    next: "by5",
  },
  {
    id: "by4c",
    speaker: "n",
    ira: "smile",
    text: "Со стула было видно, как он смотрит: не «мама это или нет», а «она останется на чай или нет». Чай она налила себе сама.",
    next: "by5",
  },
  {
    id: "by5",
    speaker: "ira",
    ira: "tender",
    text: "Нормально. Правда. Можно дышать.",
    next: "by6",
  },
  {
    id: "by6",
    speaker: "n",
    ira: "smile",
    sasha: "warm",
    music: "warm",
    text: "Потом и правда можно было. Мы не сидели в кухне три дня. Поехали. Втроём. Страна вдруг стала просто дорогой.",
    next: "by7",
  },
  {
    id: "by7",
    speaker: "n",
    bg: "castle",
    ira: "laugh",
    sasha: null,
    music: "warm",
    ambience: "none",
    cg: null,
    text: "Брест. Крепость. Кирпич тёплый даже в холод. Дима забрался на бруствер раньше нас и крикнул, что отсюда всё маленькое. Ира крикнула, что он тоже, пока не спустится. Он спустился — уже смеясь.",
    next: "by8",
  },
  {
    id: "by8",
    speaker: "n",
    bg: "river",
    ira: "smile",
    text: "Пинск. Река широкая, как пауза, в которой уже не страшно. Мы ели что-то с рук на набережной. Дима спросил Иру, умеет ли она водить. Она сказала: умею. И что он когда-нибудь тоже.",
    next: "by9",
  },
  {
    id: "by9",
    speaker: "n",
    bg: "bison",
    ira: "laugh",
    text: "Зоопарк. Кто-то из нас долго стоял у вольера и спорил, кто кого рассматривает. Дима победил: он умеет молчать дольше зубров.",
    next: "by10",
  },
  {
    id: "by10",
    speaker: "ira",
    bg: "wheat",
    ira: "tender",
    text: "Смотри. Он уже не проверяет меня каждые пять минут. Значит, можно ехать дальше.",
    next: "by11",
  },
  {
    id: "by11",
    speaker: "n",
    bg: "relatives",
    ira: "shy",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "В Минске у родных стол был накрыт так, будто нас ждали дольше, чем мы ехали. Вопросы были громкие. Ира отвечала коротко. Потом её просто докормили. Это у нас считается принятием.",
    next: "by12",
  },
  {
    id: "by12",
    speaker: "n",
    bg: "tesla",
    ira: null,
    sasha: null,
    cg: "tesla",
    music: "home",
    ambience: "car",
    text: "Перед дорогой домой мы забрали чёрную. Тихую. В бумагах — Tesla, купили здесь. В салоне пахло новым и чужим, пока Ира не села первой — по привычке Поло — и не включила печку.",
    next: "by13",
  },
  {
    id: "by13",
    speaker: "ira",
    cg: "tesla",
    text: "Тёплая Tesla. Тёпсла. Всё. Пусть в паспорте будет как хотят.",
    next: "by14",
  },
  {
    id: "by14",
    speaker: "sasha",
    sasha: "laugh",
    cg: "tesla",
    text: "Тепсла. Записали. Дима потом всё равно будет говорить «машина».",
    next: "by15",
  },
  {
    id: "by15",
    speaker: "n",
    cg: "tesla",
    text: "Мы ехали в Нижний уже не втроём. Дима остался дома. За спиной — крепость, река, вольер и стол. Впереди — кот, который даже не спросит, где мы были.",
    next: "chHome",
  },

  {
    id: "chHome",
    speaker: "n",
    bg: "rental",
    ira: null,
    sasha: null,
    cg: null,
    music: "home",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "VII", title: "Дом", hint: "свой ключ" },
    text: "",
    next: "home1",
  },
  {
    id: "home1",
    speaker: "n",
    bg: "rental",
    ira: "smile",
    sasha: null,
    music: "home",
    ambience: "home",
    text: "Сначала была съёмная. Чужие стены, наши кружки. Альф на третьи сутки нашёл батарею и больше не интересовался, чья это квартира по договору.",
    next: "home2",
  },
  {
    id: "home2",
    speaker: "ira",
    ira: "laugh",
    text: "Слышишь? Это мы. Соседям извини потом. Или не извини. Мы платим.",
    next: "home3",
  },
  {
    id: "home3",
    speaker: "n",
    ira: "smile",
    text: "Потом — своя. Ключи в миске у двери, как у людей, которые уже не играют в гостей.",
    choices: [
      { text: "Поставить миску сразу, пока не потеряли", next: "home4a", warmth: 1 },
      { text: "Сесть на пол. Коробки подождут", next: "home4b", warmth: 2 },
      { text: "Пустить Альфа первым — пусть выберет комнату", next: "home4c", warmth: 2 },
    ],
  },
  {
    id: "home4a",
    speaker: "sasha",
    sasha: "warm",
    ira: "smile",
    text: "Положил. Звякнуло. Ира сказала «дом» шёпотом, как будто слово ещё горячее.",
    next: "home5",
  },
  {
    id: "home4b",
    speaker: "ira",
    ira: "tender",
    sasha: null,
    text: "Вот. Пол — тоже мебель. Особенно если на нём уже кот.",
    next: "home5",
  },
  {
    id: "home4c",
    speaker: "n",
    ira: "laugh",
    sasha: null,
    text: "Альф пошёл в самую солнечную комнату и лёг. Мы пошли за ним. Так у нас появилась спальня.",
    next: "home5",
  },
  {
    id: "home5",
    speaker: "n",
    bg: "novoselye",
    ira: null,
    sasha: null,
    cg: "novoselye",
    text: "На стекле магазина было написано про новоселье. Мы стояли в дверях ещё без дивана — две пары ног и пакет с лампочкой. Дом начался с порога, не с мебели.",
    next: "home6",
  },
  {
    id: "home6",
    speaker: "ira",
    cg: "novoselye",
    text: "Нам к лицу. Даже если витрина имеет в виду другой диван.",
    next: "home7",
  },
  {
    id: "home7",
    speaker: "n",
    bg: "home",
    ira: "tender",
    sasha: "warm",
    cg: "cg-alf",
    text: "Вечером Альф снова нашёл колени. Тепсла стояла внизу, чёрная, уже не чужая. Нижний за окном был просто городом, в котором мы живём.",
    next: "chWant",
  },

  {
    id: "chWant",
    speaker: "n",
    bg: "future",
    ira: null,
    sasha: null,
    cg: null,
    music: "quiet",
    ambience: "home",
    ui: "chapter",
    chapter: { n: "VIII", title: "Наш", hint: "ещё одно место за столом" },
    text: "",
    next: "want1",
  },
  {
    id: "want1",
    speaker: "n",
    bg: "future",
    ira: "thoughtful",
    sasha: null,
    music: "quiet",
    ambience: "home",
    text: "Тихий вечер. Альф тяжёлый на пледе. Чай остывает. И в этой тишине слово вылезло само — не как план, как погода.",
    next: "want2",
  },
  {
    id: "want2",
    speaker: "ira",
    ira: "tender",
    text: "Саш.",
    next: "want3",
  },
  {
    id: "want3",
    speaker: "sasha",
    sasha: "warm",
    ira: "tender",
    text: "Я тоже думал.",
    next: "want4",
  },
  {
    id: "want4",
    speaker: "n",
    ira: "shy",
    sasha: "warm",
    text: "Мы сказали это почти вместе. Потом замолчали, потому что дальше уже не слова, а страх и радость в одном стакане.",
    choices: [
      { text: "Взять её за руку и не обещать дату", next: "want5a", warmth: 2 },
      { text: "«Мне страшно. И хочется.»", next: "want5b", warmth: 2 },
      { text: "«Дима от этого не станет меньше.»", next: "want5c", warmth: 1 },
    ],
  },
  {
    id: "want5a",
    speaker: "ira",
    ira: "tender",
    sasha: "warm",
    text: "Не надо дату. Надо не делать вид, что мы это не сказали.",
    next: "want6",
  },
  {
    id: "want5b",
    speaker: "ira",
    ira: "laugh",
    sasha: "awkward",
    text: "Тогда мы одинаковые. Это удобно. Остальное — как Поло и договор: поедем, когда поедем.",
    next: "want6",
  },
  {
    id: "want5c",
    speaker: "ira",
    ira: "tender",
    sasha: "warm",
    text: "Не станет. Он первый. Это не конкурс.",
    next: "want6",
  },
  {
    id: "want6",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "future",
    text: "На столе две кружки. Между ними — место. Пока пустое. Уже не случайное.",
    next: "fin1",
  },

  {
    id: "fin1",
    speaker: "n",
    bg: "sunset",
    ira: null,
    sasha: null,
    cg: null,
    music: "warm",
    ambience: "none",
    text: "Потом был снег за окном, как в ту первую ночь, только дворники уже не чужие.",
    next: "fin2",
  },
  {
    id: "fin2",
    speaker: "n",
    bg: "title",
    music: "title",
    ambience: "snow",
    text: "А если честно — история ещё не кончилась. Просто в ней уже есть место ещё для одного человека.",
    ending: "together",
  },

  {
    id: "numbers1",
    speaker: "n",
    bg: "street",
    ira: "smile",
    sasha: null,
    music: "snow",
    ambience: "snow",
    cg: null,
    text: "На улице снег стал мельче. Мы остановились под козырьком, как два человека, которые ещё не имеют права на долгие прощания.",
    next: "numbers2",
  },
  {
    id: "numbers2",
    speaker: "ira",
    ira: "tender",
    text: "Напишите. Не завтра утром, ладно? Завтра утром все герои становятся осторожными. Напишите вечером.",
    next: "numbers3",
  },
  {
    id: "numbers3",
    speaker: "sasha",
    sasha: "warm",
    text: "Вечером. Пока снег ещё помнит нас.",
    next: "numbers4",
  },
  {
    id: "numbers4",
    speaker: "n",
    ira: "smile",
    sasha: null,
    bg: "title",
    text: "Она ушла первой. Свитер мелькнул в жёлтом окне такси. В кармане лежал номер — тёплый, как невыпитая чашка.",
    ending: "numbers",
  },

  {
    id: "almost1",
    speaker: "n",
    bg: "cafe-brick",
    ira: "thoughtful",
    music: "quiet",
    ambience: "cafe",
    cg: null,
    text: "Мы попрощались вежливо, как умеют взрослые, когда боятся назвать вечер важным.",
    next: "almost2",
  },
  {
    id: "almost2",
    speaker: "n",
    ira: null,
    bg: "street",
    ambience: "snow",
    text: "Уже на улице я нашёл в кармане пальто закладку. На ней было одно слово её почерком: «Ещё».",
    next: "almost3",
  },
  {
    id: "almost3",
    speaker: "n",
    bg: "title",
    text: "Не номер. Не адрес. Просто «ещё». Иногда этого хватает, чтобы вернуться в ту же кофейню через неделю.",
    ending: "almost",
  },
];

export const STORY: Record<string, StoryNode> = Object.fromEntries(nodes.map((n) => [n.id, n]));
export const START_ID = "ch1";

export function resolveRoute(warmth: number): string {
  if (warmth >= 7) return "together1";
  if (warmth >= 4) return "numbers1";
  return "almost1";
}

export const CHAPTERS: {
  id: string;
  n: string;
  title: string;
  hint: string;
  need?: string;
  warmth?: number;
}[] = [
  { id: "ch1", n: "I", title: "МЭТЧ", hint: "приложение" },
  { id: "ch2", n: "II", title: "Кофейня", hint: "первый вечер" },
  { id: "ch3", n: "III", title: "Договор", hint: "две недели спустя", need: "together", warmth: 8 },
  { id: "chDrive", n: "IV", title: "За рулём", hint: "её Поло", need: "together", warmth: 8 },
  { id: "chHalf", n: "V", title: "Полгода", hint: "сначала кот", need: "together", warmth: 8 },
  { id: "chBy", n: "VI", title: "Беларусь", hint: "сначала порог", need: "together", warmth: 8 },
  { id: "chHome", n: "VII", title: "Дом", hint: "свой ключ", need: "together", warmth: 8 },
  { id: "chWant", n: "VIII", title: "Наш", hint: "ещё одно место", need: "together", warmth: 8 },
];

export const ENDING_TITLE: Record<string, string> = {
  together: "Наша история",
  numbers: "Вечером",
  almost: "Ещё",
  missed: "Стекло",
};

export const ENDING_BLURB: Record<string, string> = {
  together: "Полгода. Потом порог в Барановичах. Потом Брест, Пинск, дом и слово «наш».",
  numbers: "Номер в кармане. Вечер не закрыт, только поставлен на паузу.",
  almost: "Закладка с одним словом. Иногда этого достаточно.",
  missed: "Вы не сели. История осталась тёплым окном.",
};
